### ISSUE TITLE
后置耳机孔问题

### ISSUE THREAD

**Issue by D-Jancy** [littlesum/nuc9hacktosh-config#1]
您定制的声卡驱动，虽然成功驱动了光口，多内建了一个数字音频输出，但后置耳机孔插耳机没办法输出声音，期待大佬的修复

**Comment by littlesum** [comment]
我抓的数据记得后置好像没有耳机🤔？只有前置是二合一接口，我记得测试的时候，如果插入前置接口，后面的自动就不能用了。 我找找图

**Comment by littlesum** [comment]
![image](https://github.com/littlesum/nuc9hacktosh-config/assets/22040751/8c69a77d-a121-4037-8f71-b976634614ab)

**Comment by littlesum** [comment]
![image](https://github.com/littlesum/nuc9hacktosh-config/assets/22040751/88f64f24-04e5-4782-90f0-433ba4621be0)

**Comment by littlesum** [comment]
> 您定制的声卡驱动，虽然成功驱动了光口，多内建了一个数字音频输出，但后置耳机孔插耳机没办法输出声音，期待大佬的修复

后面耳机应该是有声音的，你如果用了前置，后面就没声音了，只能同时用一个。

**Comment by littlesum** [comment]
我手里没有二合一设备，没办法测试，只能看数据搞。 我有空了再试试看是不是把啥路径掉了，所以没声，我主要就是为了那个光口才定制的驱动，看光口能用就没管了！

**Comment by D-Jancy** [comment]
> 我手里没有二合一设备，没办法测试，只能看数据搞。 我有空了再试试看是不是把啥路径掉了，所以没声，我主要就是为了那个光口才定制的驱动，看光口能用就没管了！

我没有两个耳机孔都插，只差了后置耳机孔也是没有输出的，windows下是可以的，用小兵大佬的定制efi的驱动和pic补丁也是可以驱动后置耳机孔输出的，只是没了光口

**Comment by D-Jancy** [comment]
小兵大佬的pci补丁路径是PciRoot(0x0)/Pci(0x1b,0x0)，您的是PciRoot(0x0)/Pci(0x1F,0x3)

**Comment by littlesum** [comment]
> 小兵大佬的pci补丁路径是PciRoot(0x0)/Pci(0x1b,0x0)，您的是PciRoot(0x0)/Pci(0x1F,0x3)

我今天测试了，肯定有声音。前后都有,不过没有麦克风可以测试。 我的pcid才是对的 ，我下面有图

**Comment by littlesum** [comment]
<img width="1812" alt="iShot_2023-09-28_11 43 11" src="https://github.com/littlesum/nuc9hacktosh-config/assets/22040751/29088631-f073-40b6-8fc6-05b0e3383856">
你看看你的hackintool 里面有声卡的pcid
